/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.interfaces;

import com.beans.TabelaArtistaBean;
import com.beans.TabelaCDsBean;
import com.beans.TabelaGeneroBean;
import com.dao.Artista_dao;
import com.dao.CDs_dao;
import com.dao.Genero_dao;

/**
 *
 * @author andre
 */
public class FrCDs extends javax.swing.JFrame {

    /**
     * Creates new form FrCadastroLivro
     */
    public FrCDs() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        Genero_dao g = new Genero_dao();
        Artista_dao a = new Artista_dao();
        CDs_dao c = new CDs_dao();
        
        for(TabelaGeneroBean ge: g.findAll()){
            g_box.addItem(ge);
        }
        for(TabelaArtistaBean ar: a.findAll()){
            g_box2.addItem(ar);
        }
        
        painel1.setVisible(false);
        btn_edit.setEnabled(false);
        btn_excluir.setEnabled(false);
        btn_cad.setEnabled(true);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nm_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        vr_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_edit = new javax.swing.JButton();
        btn_cad = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        g_box = new javax.swing.JComboBox<>();
        g_box2 = new javax.swing.JComboBox<>();
        painel1 = new javax.swing.JPanel();
        lb_c = new javax.swing.JLabel();
        cd_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CD");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nome");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Valor Unit");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Genero");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Artista");

        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagens/Edit_16x16.png"))); // NOI18N
        btn_edit.setText("Editar");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_cad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagens/Add_16x16.png"))); // NOI18N
        btn_cad.setText("Cadastrar");
        btn_cad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadActionPerformed(evt);
            }
        });

        btn_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagens/Delete_16x16.png"))); // NOI18N
        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        g_box.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                g_boxItemStateChanged(evt);
            }
        });
        g_box.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                g_boxMouseClicked(evt);
            }
        });

        g_box2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                g_box2ItemStateChanged(evt);
            }
        });
        g_box2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                g_box2MouseClicked(evt);
            }
        });

        lb_c.setText("ID");

        cd_txt.setEditable(false);

        javax.swing.GroupLayout painel1Layout = new javax.swing.GroupLayout(painel1);
        painel1.setLayout(painel1Layout);
        painel1Layout.setHorizontalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel1Layout.createSequentialGroup()
                .addComponent(lb_c)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cd_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );
        painel1Layout.setVerticalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_c)
                    .addComponent(cd_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nm_txt))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_cad))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(g_box2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(vr_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(g_box, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(nm_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(painel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(vr_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(g_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(g_box2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_edit)
                    .addComponent(btn_cad)
                    .addComponent(btn_excluir))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void RetornaDados(TabelaCDsBean c){
        painel1.setVisible(true);
        btn_edit.setEnabled(true);
        btn_excluir.setEnabled(true);
        btn_cad.setEnabled(false);
        cd_txt.setText(String.valueOf(c.getId()));
        nm_txt.setText(c.getTitulo());
        vr_txt.setText(String.valueOf(c.getPreco()));
        g_box.getModel().setSelectedItem(c.getGenero());
        g_box2.getModel().setSelectedItem(c.getArtista());
    }
    
    
    
    
    private void btn_cadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadActionPerformed
        // TODO add your handling code here:
        
        CDs_dao c = new CDs_dao();
        TabelaCDsBean p = new TabelaCDsBean();
        
        TabelaGeneroBean ge = (TabelaGeneroBean) g_box.getSelectedItem();
        TabelaArtistaBean au = (TabelaArtistaBean) g_box2.getSelectedItem();

        //p.setId(Integer.parseInt(id_txt.getText()));
        p.setTitulo(nm_txt.getText());
        p.setPreco(Double.parseDouble(vr_txt.getText()));
        p.setGenero(ge);
        p.setArtista(au);
        c.create(p);

        nm_txt.setText("");
        //isqn_txt.setText("");
        vr_txt.setText("");
        cd_txt.setText("");
        g_box.setSelectedIndex(0);
        g_box2.setSelectedIndex(0);
        
    }//GEN-LAST:event_btn_cadActionPerformed

    private void g_boxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_g_boxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_g_boxItemStateChanged

    private void g_boxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g_boxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_g_boxMouseClicked

    private void g_box2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_g_box2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_g_box2ItemStateChanged

    private void g_box2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g_box2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_g_box2MouseClicked

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        CDs_dao c = new CDs_dao();
        TabelaCDsBean p = new TabelaCDsBean();
        
        TabelaGeneroBean ge = (TabelaGeneroBean) g_box.getSelectedItem();
        TabelaArtistaBean au = (TabelaArtistaBean) g_box2.getSelectedItem();

        p.setId(Integer.parseInt(cd_txt.getText()));
        p.setTitulo(nm_txt.getText());
        p.setPreco(Double.parseDouble(vr_txt.getText()));
        p.setGenero(ge);
        p.setArtista(au);
        c.update(p);

        nm_txt.setText("");
        //isqn_txt.setText("");
        vr_txt.setText("");
        cd_txt.setText("");
        g_box.setSelectedIndex(0);
        g_box2.setSelectedIndex(0);
        painel1.setVisible(false);
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        // TODO add your handling code here:
        CDs_dao c = new CDs_dao();
        TabelaCDsBean p = new TabelaCDsBean();

        p.setId(Integer.parseInt(cd_txt.getText()));
        c.delete(p);

        nm_txt.setText("");
        //isqn_txt.setText("");
        vr_txt.setText("");
        cd_txt.setText("");
        g_box.setSelectedIndex(0);
        g_box2.setSelectedIndex(0);
        painel1.setVisible(false);
    }//GEN-LAST:event_btn_excluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrCDs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrCDs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrCDs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCDs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrCDs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cad;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JTextField cd_txt;
    private javax.swing.JComboBox<Object> g_box;
    private javax.swing.JComboBox<Object> g_box2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lb_c;
    private javax.swing.JTextField nm_txt;
    private javax.swing.JPanel painel1;
    private javax.swing.JTextField vr_txt;
    // End of variables declaration//GEN-END:variables
}
