/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.interfaces;

import com.beans.TabelaArtistaBean;
import com.beans.TabelaCDsBean;
import com.beans.TabelaGeneroBean;
import com.dao.Artista_dao;
import com.dao.CDs_dao;
import com.dao.Genero_dao;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andre
 */
public class FrPrincipal extends javax.swing.JFrame {
    private int form;
    /**
     * Creates new form Principal
     */
    public FrPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.Painel1.setVisible(false);
        cancel_btn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Painel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        busca_txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cancel_btn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Painel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Consulta"));

        jLabel1.setText("ID:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagens/Search_16x16.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cancel_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagens/Preview_16x16.png"))); // NOI18N
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel1Layout = new javax.swing.GroupLayout(Painel1);
        Painel1.setLayout(Painel1Layout);
        Painel1Layout.setHorizontalGroup(
            Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(busca_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancel_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Painel1Layout.setVerticalGroup(
            Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(busca_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Arquivo");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cadastrar");

        jMenuItem2.setText("Artista");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Genero");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("CDs");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Consultar");

        jMenuItem5.setText("CDs");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Artista");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Genero");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Painel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Painel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        form = 0;
        busca_txt.setText("");
        Painel1.setVisible(true);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setNumRows(0);
                model.setColumnCount(0);
                model.addColumn("ID");
                model.addColumn("Titulo");
                model.addColumn("Preço");
                model.addColumn("ID Artista");
                model.addColumn("Artista");
                model.addColumn("ID Genero");
                model.addColumn("Genero");
        CDs_dao cd = new CDs_dao();
        
        for (TabelaCDsBean p : cd.findAll()) {
            model.addRow(new Object[]{
                p.getId(),
                p.getTitulo(),
                p.getPreco(),
                p.getArtista().getId(),
                p.getArtista().getNome(),
                p.getGenero().getId(),
                p.getGenero().getNome()
            });
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        form = 1;
        busca_txt.setText("");
        Painel1.setVisible(true);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setNumRows(0);
                model.setColumnCount(0);
                model.addColumn("ID");
                model.addColumn("Nome");
        Artista_dao ar = new Artista_dao();
        
        for (TabelaArtistaBean p : ar.findAll()) {
            model.addRow(new Object[]{
                p.getId(),
                p.getNome()
            });
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        form = 2;
        busca_txt.setText("");
        Painel1.setVisible(true);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setNumRows(0);
                model.setColumnCount(0);
                model.addColumn("ID");
                model.addColumn("Nome");
        Genero_dao ge = new Genero_dao();
        
        for (TabelaGeneroBean p : ge.findAll()) {
            model.addRow(new Object[]{
                p.getId(),
                p.getNome()
            });
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new FrArtista().setVisible(true);
            Painel1.setVisible(false);
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setNumRows(0);
                model.setColumnCount(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        jTable1.setDefaultEditor(Object.class, null);
        if(evt.getClickCount() == 2){
            select_jtable();
            Painel1.setVisible(false);
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setNumRows(0);
                model.setColumnCount(0);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new FrGenero().setVisible(true);
            Painel1.setVisible(false);
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setNumRows(0);
                model.setColumnCount(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new FrCDs().setVisible(true);
            Painel1.setVisible(false);
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setNumRows(0);
                model.setColumnCount(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setNumRows(0);
        PreparedStatement stmt = null;
        ResultSet rs = null;
        cancel_btn.setVisible(true);
            
            switch (form) {
                case 0:
                    TabelaCDsBean c = new TabelaCDsBean();
                    CDs_dao cd = new CDs_dao();
                    c.setId(Integer.parseInt(busca_txt.getText()));
                    for (TabelaCDsBean p : cd.findByPrimaryKey(c)) {
                    model.addRow(new Object[]{
                    p.getId(),
                    p.getTitulo(),
                    p.getPreco(),
                    p.getArtista().getId(),
                    p.getArtista().getNome(),
                    p.getGenero().getId(),
                    p.getGenero().getNome()
                    });
                    }
                break;
                case 1:
                    TabelaArtistaBean a = new TabelaArtistaBean();
                    Artista_dao ar = new Artista_dao();
                    a.setId(Integer.parseInt(busca_txt.getText()));
                    for (TabelaArtistaBean p : ar.findByPrimaryKey(a)) {
                    model.addRow(new Object[]{
                    p.getId(),
                    p.getNome()
                    });
                    }
                break;
                case 2:
                    TabelaGeneroBean g = new TabelaGeneroBean();
                    Genero_dao ge = new Genero_dao();
                    g.setId(Integer.parseInt(busca_txt.getText()));
                    for (TabelaGeneroBean p : ge.findByPrimaryKey(g)) {
                    model.addRow(new Object[]{
                    p.getId(),
                    p.getNome()
                    });
                    }                
                break;
                default:
                    JOptionPane.showMessageDialog(null, "Opção Invalida!!!");
            }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setNumRows(0);
        PreparedStatement stmt = null;
        ResultSet rs = null;
        busca_txt.setText("");
        cancel_btn.setVisible(false);
            
            switch (form) {
                case 0:
                    TabelaCDsBean c = new TabelaCDsBean();
                    CDs_dao cd = new CDs_dao();
                    for (TabelaCDsBean p : cd.findAll()) {
                    model.addRow(new Object[]{
                    p.getId(),
                    p.getTitulo(),
                    p.getPreco(),
                    p.getArtista().getId(),
                    p.getArtista().getNome(),
                    p.getGenero().getId(),
                    p.getGenero().getNome()
                    });
                    }
                break;
                case 1:
                    TabelaArtistaBean a = new TabelaArtistaBean();
                    Artista_dao ar = new Artista_dao();
                    for (TabelaArtistaBean p : ar.findAll()) {
                    model.addRow(new Object[]{
                    p.getId(),
                    p.getNome()
                    });
                    }
                break;
                case 2:
                    TabelaGeneroBean g = new TabelaGeneroBean();
                    Genero_dao ge = new Genero_dao();
                    for (TabelaGeneroBean p : ge.findAll()) {
                    model.addRow(new Object[]{
                    p.getId(),
                    p.getNome()
                    });
                    }                
                break;
                default:
                    JOptionPane.showMessageDialog(null, "Opção Invalida!!!");
            }
        
    }//GEN-LAST:event_cancel_btnActionPerformed

    public void select_jtable(){
            int linha = jTable1.getSelectedRow();
            PreparedStatement stmt = null;
            ResultSet rs = null;
            
            switch (form) {
                case 0:
                    TabelaCDsBean c = new TabelaCDsBean();
                    TabelaArtistaBean ar = new TabelaArtistaBean();
                    TabelaGeneroBean ge = new TabelaGeneroBean();
                    FrCDs cd = new FrCDs();
                    c.setId((int) jTable1.getValueAt(linha, 0));
                    c.setTitulo(jTable1.getValueAt(linha, 1).toString());
                    c.setPreco((double) jTable1.getValueAt(linha, 2));
                    ar.setId((int) jTable1.getValueAt(linha, 3));
                    ar.setNome(jTable1.getValueAt(linha, 4).toString());
                    ge.setId((int) jTable1.getValueAt(linha, 5));
                    ge.setNome(jTable1.getValueAt(linha, 6).toString());
                    c.setArtista(ar);
                    c.setGenero(ge);
                    
                    cd.setVisible(true);
                    cd.RetornaDados(c);
                break;
                case 1:
                    TabelaArtistaBean a = new TabelaArtistaBean();
                    FrArtista artista = new FrArtista();
                    a.setId((int) jTable1.getValueAt(linha, 0));
                    a.setNome(jTable1.getValueAt(linha, 1).toString());
                    artista.setVisible(true);
                    artista.RetornaDados(a);
                break;
                case 2:
                    TabelaGeneroBean g = new TabelaGeneroBean();
                    FrGenero genero = new FrGenero();
                    g.setId((int) jTable1.getValueAt(linha, 0));
                    g.setNome(jTable1.getValueAt(linha, 1).toString());
                    genero.setVisible(true);
                    genero.RetornaDados(g);
                break;
                default:
                    JOptionPane.showMessageDialog(null, "Opção Invalida!!!");
            }
            
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel1;
    private javax.swing.JTextField busca_txt;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
